### ISSUE TITLE
Please include index.scss in npm package 

### ISSUE THREAD

**Issue by benwoodward** [pd4d10/hashmd#16]
I use Sass imports to import styles from npm packages, e.g.:

```scss
<style lang="scss" global>
@import "bytemd/dist/index.min";

.bytemd {
  border: none;
}
.bytemd-editor {
  .CodeMirror {
    background: transparent;
    padding: 0;
    font-size: 17px;
  }
  .CodeMirror-cursor {
    border-width: 2px;
    border-color: #2DBDEC;
    height: 25px !important;
  }
}
</style>
```

My rollup config contains:

```js
import { scss, globalStyle } from 'svelte-preprocess';

// snip

      svelte({
        generate: 'dom',
        hydratable: true,
        // enable run-time checks when not in production
        dev: !production,
        css: css => {
          css.write('css/app.css');
        },
        preprocess: [
          scss(),
          globalStyle()
        ],
      }),

// snip
```

For some reason, Svelte keeps complaining that it can't find the file. I've tried using "bytemd/dist/index.min", "bytemd/dist/index.min.css", "bytemd/dist/index.css" to no avail.

It'd be great if you could include the Sass in the npm package `dist/` directory as well as the CSS, as this would solve my problem (`node-sass` / `svelte-preprocess` has no trouble importing `.sass` files). 

EDIT: It's actually due to [this issue](https://github.com/sveltejs/svelte-preprocess/issues/141), but through testing I found that importing the bytemd .scss file directly still wouldn't work because it itself imports .css files. I'm just gonna find another solution for the time-being and hope that this bug is fixed in `svelte-preprocess` eventually. 

EDIT: Ok, I resolved this issue in my codebase by using `atImport()`:

```js
// rollup.config.js
import sveltePreprocess from 'svelte-preprocess';
import atImport from 'postcss-import';

// snip

        preprocess: sveltePreprocess({
          sourceMap: !production,
          defaults: {
            style: 'scss'
          },
          sass: {
            includePaths: ['src'],
          },
          postcss: {
            plugins: [atImport({path: ['src/styles']})],
          },
        }),

// snip
```
