### ISSUE TITLE
How to customize toolbar?

### ISSUE THREAD

**Issue by imageslr** [pd4d10/hashmd#92]

**Comment by bmitzkus** [comment]
I figured out how to write custom plugins and add them to the left toolbar. How can existing toolbar icons be removed from both left and right toolbars? I am using the react component<details>
<summary> custom plugin implementation </summary>

```javascript
import React from "react";
import { Editor } from "@bytemd/react";
import "bytemd/dist/index.min.css";
import { Undo, Redo } from "@material-ui/icons";
import { renderToString } from "react-dom/server";

const plugins = [undoRedo()];

export function TextEditor() {
  const [value, setValue] = React.useState("foo");
  return (
    <Editor
      value={value}
      plugins={plugins}
      onChange={(v) => {
        setValue(v);
      }}
      mode="split"
    />
  );
}

function undoRedo() {
  return {
    actions: [
      {
        title: "Undo",
        icon: renderToString(<Undo />),
        handler: {
          type: "action",
          click: ({ editor }) => editor.undo()
        }
      },
      {
        title: "Redo",
        icon: renderToString(<Redo />),
        handler: {
          type: "action",
          click: ({ editor }) => editor.redo()
        }
      }
    ]
  };
}
```
</details>

**Comment by imageslr** [comment]
@Hvitgar 
I Think you can fork the code and modify [this component](https://github.com/bytedance/bytemd/blob/main/packages/bytemd/src/toolbar.svelte), which defines both left and right icons.

**Comment by bmitzkus** [comment]
@imageslr sure, thank you, but modifying the source code would be my last resort of customization. Just exposing the list of Plugins on both right and left toolbar as props and setting the current config as default would already make the toolbar fully configurable.

A `hidden` flag exists already on the default plugins, but it cannot be set from outside.

Is this a desirable feature? I could implement it and write a PR

**Comment by symeus-sgs** [comment]
@Hvitgar Would it be possible to implement this? Specifically looking to remove the full screen and the link to the source from the right-hand side.

**Comment by bmitzkus** [comment]
Since there was no response from the maintainers I won't put any work in this. However, you can "hack" around it by using the css classes tippy assigns to the buttons. Example below hides the features "Quote", "Code" and "Code Block" from the left toolbar and the "Github Icon" from the right toolbar.

```css
/* Toolbar Customization Hacks */

/*
  As default items in the left toolbar are not customizable,
  the order of these icons will be the same:
  0. Headings
  1. Bold
  2. Italic
  3. Quote
  4. Link
  5. ??? (does not exist for some reason)
  6. Code
  7. Code Block
  8. Bullet list
  9. Numbered list
*/

.bytemd-toolbar-left [bytemd-tippy-path='3'] {
  display: none;
}
.bytemd-toolbar-left [bytemd-tippy-path='6'] {
  display: none;
}
.bytemd-toolbar-left [bytemd-tippy-path='7'] {
  display: none;
}

/*
  As the right toolbar is not customizable,
  the order of icons will be the same:
  0. Table of Contents
  1. Help
  2. Write Only
  3. Preview Only
  4. Fullscreen
  5. Github Permalink
*/

/* disable Github Permalink */
.bytemd-toolbar-right [bytemd-tippy-path='5'] {
  display: none;
}

/* End toolbar customization hacks */

```

@symeus-sgs hiding the fullscreen and github buttons should work using indices 4/5 on the right toolbar. However, this whole approach will fail if they reorder, add or remove buttons in a future release.
